version: "2.2"

services:
  q2bank:
    container_name: q2bank
    build:
      context: ./
      dockerfile: ./dockerfile.yaml
    ports:
      - '1323:1323'
    volumes:
      - ./:/app
    environment:
      - APP_NODE=prod
      - PORT=1323
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - SECRET=secret
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    expose:
      - 5432
    volumes: 
      - db:/var/lib/postgresql/data


volumes:
  db:
    driver: local