version: "2.2"

services:
  bff-answerfy:
    container_name: bff-answerfy
    build:
      context: ./
      dockerfile: ./dockerfile.yaml
    ports:
      - '1323:1323'
    volumes:
      - ./:/app
    environment:
      - APP_NODE=prod
      - PORT=1323
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - JWT_SECRET=secret
      - OPENAI_API_KEY=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
      - OPENAI_URL=http://localhost:3000/chatgpt
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    expose:
      - 5432
    volumes: 
      - db:/var/lib/postgresql/data


volumes:
  db:
    driver: local